# Borrowed from OSG...

# Required Vars:
# ${LIB_NAME}
# ${LIB_PUBLIC_HEADERS}

SET(INSTALL_INCDIR include)
SET(INSTALL_BINDIR bin)
IF(WIN32)
    SET(INSTALL_LIBDIR bin)
    SET(INSTALL_ARCHIVEDIR lib)
ELSE(WIN32)
    SET(INSTALL_LIBDIR lib${LIB_POSTFIX})
    SET(INSTALL_ARCHIVEDIR lib${LIB_POSTFIX})
ENDIF(WIN32)

SET(HEADERS_GROUP "Header Files")

SOURCE_GROUP(
    ${HEADERS_GROUP}
    FILES ${LIB_PUBLIC_HEADERS}
)

INSTALL(
    TARGETS ${LIB_NAME}
    EXPORT  osgaudio-targets
    RUNTIME DESTINATION ${INSTALL_BINDIR} COMPONENT libosgaudio
    LIBRARY DESTINATION ${INSTALL_LIBDIR} COMPONENT libosgaudio
    ARCHIVE DESTINATION ${INSTALL_ARCHIVEDIR} COMPONENT libosgaudio-dev
)

# FIXME: Do not run for OS X framework
INSTALL(
    FILES       ${LIB_PUBLIC_HEADERS}
    DESTINATION ${INSTALL_INCDIR}/${LIB_NAME}
    COMPONENT libosgaudio-dev
)

# install backend headers to their subfolder
# FMOD
IF(0_ENABLE_SUBSYSTEM_FMOD)
INSTALL(
    FILES       ${LIB_PUBLIC_HEADERS_SUBSYSTEM}
    DESTINATION ${INSTALL_INCDIR}/${LIB_NAME}/BackendFMOD
    COMPONENT libosgaudio-dev
)
ENDIF(0_ENABLE_SUBSYSTEM_FMOD)

# OpenAL++
IF(0_ENABLE_SUBSYSTEM_OPENAL)
INSTALL(
    FILES       ${LIB_PUBLIC_HEADERS_SUBSYSTEM}
    DESTINATION ${INSTALL_INCDIR}/${LIB_NAME}/BackendOpenALpp
    COMPONENT libosgaudio-dev
)
ENDIF(0_ENABLE_SUBSYSTEM_OPENAL)
