# INSTALL commands, borrowed from OSG's ModuleInstall, for executables

# Required Vars:
# ${TARGET_TARGETNAME}
# ${COMPONENT_NAME}

IF(WIN32)
	SET(INSTALL_INCDIR Include)
	SET(INSTALL_BINDIR Bin)
    SET(INSTALL_LIBDIR Bin)
    SET(INSTALL_ARCHIVEDIR Lib)
ELSE(WIN32)
	SET(INSTALL_INCDIR include)
	SET(INSTALL_BINDIR bin)
    SET(INSTALL_LIBDIR lib${LIB_POSTFIX})
    SET(INSTALL_ARCHIVEDIR lib${LIB_POSTFIX})
ENDIF(WIN32)


INSTALL(
    TARGETS ${TARGET_TARGETNAME}
    RUNTIME DESTINATION "${INSTALL_BINDIR}" COMPONENT ${COMPONENT_NAME}
    #LIBRARY DESTINATION "${INSTALL_LIBDIR}" COMPONENT libpvle
    #ARCHIVE DESTINATION "${INSTALL_ARCHIVEDIR}" COMPONENT libpvle-dev
)

# # FIXME: Do not run for OS X framework
# INSTALL(
    # FILES ${LIB_PUBLIC_HEADERS}
    # DESTINATION "${INSTALL_INCDIR}/${LIB_NAME}"
    # COMPONENT libpvle-dev
# )
